// SciGPU M4 top — thin shell for lint/elaboration/synthesis smoke.
module scigpu_m4_top #(
  parameter int unsigned SGPR_COUNT = 64,
  parameter int unsigned VGPR_COUNT = 32,
  parameter int unsigned SIMD_LANES = 8,
  parameter int unsigned RESIDENT_WAVEFRONTS_PER_CU = 4,
  parameter int unsigned PMC_WIDTH  = 64
) (
  input  logic clk, input logic rst,
  output logic if_req_valid, output logic [63:0] if_req_pc,
  input  logic if_req_ready,
  input  logic if_rsp_valid, input logic [63:0] if_rsp_insn,
  input  logic if_rsp_error, output logic if_rsp_ready,
  input  logic wf_launch_valid, output logic wf_launch_ready,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] wf_launch_slot,
  input  logic [63:0] wf_entry_pc, input logic [63:0] wf_code_words,
  input  logic [31:0] wf_wg_x, input logic [31:0] wf_exec_mask,
  input  logic [8:0]  wf_vgpr_req, input logic [8:0] wf_sgpr_req,
  output logic wf_completion_valid, input logic wf_completion_ready,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] wf_completion_slot,
  output logic wf_completion_fault,
  output logic [5:0]  wf_completion_fault_code,
  output logic [63:0] wf_completion_pc,
  output logic [63:0] wf_completion_retired_count,
  input  logic sgpr_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sgpr_init_slot,
  input  logic [7:0]  sgpr_init_addr, input logic [31:0] sgpr_init_data,
  output logic sgpr_init_ready,
  input  logic pred_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] pred_init_slot,
  input  logic [3:0]  pred_init_addr, input logic [31:0] pred_init_data,
  output logic pred_init_ready,
  input  logic vgpr_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] vgpr_init_slot,
  input  logic [7:0]  vgpr_init_addr, input logic [4:0] vgpr_init_lane,
  input  logic [31:0] vgpr_init_data, output logic vgpr_init_ready,
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_allocated,
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_issueable,
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_inflight,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] dbg_rr_ptr,
  output logic sched_issue_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sched_issue_wfid,
  output logic [63:0] sched_issue_pc, sched_issue_insn,
  output logic [1:0]  sched_issue_pipe,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sched_rr_before,
  sched_rr_after,
  output logic [31:0] dbg_resident_count, dbg_ready_count,
  dbg_issueable_count,
  output logic [PMC_WIDTH-1:0] PMC_CYCLES, PMC_RESIDENT_CYCLES,
    PMC_ISSUE_CYCLES, PMC_SCALAR_ISSUES, PMC_VECTOR_ISSUES,
    PMC_NO_ISSUE_CYCLES, PMC_FETCH_WAIT_CYCLES, PMC_PIPE_BUSY_CYCLES,
    PMC_WAVEFRONTS_LAUNCHED, PMC_WAVEFRONTS_COMPLETED,
    PMC_WAVEFRONTS_FAULTED, PMC_CONTEXT_SWITCHES,
  output logic trace_s_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] trace_s_wfid,
  output logic [63:0] trace_s_pc, trace_s_insn, trace_s_next_pc,
  output logic trace_s_sgpr_we, output logic [7:0] trace_s_sgpr_addr,
  output logic [31:0] trace_s_sgpr_wdata,
  output logic trace_v_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] trace_v_wfid,
  output logic [63:0] trace_v_pc, trace_v_insn, trace_v_next_pc,
  output logic [31:0] trace_v_exec_mask, trace_v_effective_mask,
  output logic [3:0]  trace_v_pred_idx,
  output logic trace_v_we, output logic [7:0] trace_v_addr,
  output logic [31:0] trace_v_write_mask,
  output logic [63:0] dbg_last_compl_pc,
  output scigpu_types_pkg::state_e dbg_state,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] dbg_wf_sel,
  input  logic [7:0]  dbg_sgpr_addr, output logic [31:0] dbg_sgpr_data,
  input  logic [3:0]  dbg_pred_addr, output logic [31:0] dbg_pred_data,
  input  logic [7:0]  dbg_vgpr_addr, input logic [4:0] dbg_vgpr_lane,
  output logic [31:0] dbg_vgpr_data
);
  scigpu_m4_cu #(
    .SGPR_COUNT(SGPR_COUNT), .VGPR_COUNT(VGPR_COUNT),
    .SIMD_LANES(SIMD_LANES),
    .RESIDENT_WAVEFRONTS_PER_CU(RESIDENT_WAVEFRONTS_PER_CU),
    .PMC_WIDTH(PMC_WIDTH)
  ) u_core (.* );
endmodule
