// SciGPU M5 — top-level wrapper (thin shell over the M5 CU).
// Same external contract as scigpu_m4_top plus: divergence PMCs,
// mask-control trace stream, predicate-write trace fields, per-slot
// mask-stack debug taps, MASK_STACK_DEPTH parameter.
module scigpu_m5_top #(
  parameter int unsigned SGPR_COUNT = 64,
  parameter int unsigned VGPR_COUNT = 32,
  parameter int unsigned SIMD_LANES = 8,
  parameter int unsigned RESIDENT_WAVEFRONTS_PER_CU = 4,
  parameter int unsigned MASK_STACK_DEPTH = 32,
  parameter int unsigned PMC_WIDTH = 64
) (
  input  logic clk, input logic rst,
  // instruction fetch channel
  output logic if_req_valid, output logic [63:0] if_req_pc,
  input  logic if_req_ready,
  input  logic if_rsp_valid, input  logic [63:0] if_rsp_insn,
  input  logic if_rsp_error, output logic        if_rsp_ready,
  // launch channel
  input  logic wf_launch_valid, output logic wf_launch_ready,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] wf_launch_slot,
  input  logic [63:0] wf_entry_pc, input logic [63:0] wf_code_words,
  input  logic [31:0] wf_wg_x, input logic [31:0] wf_exec_mask,
  input  logic [8:0]  wf_vgpr_req, input logic [8:0] wf_sgpr_req,
  // completion channel
  output logic wf_completion_valid, input logic wf_completion_ready,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] wf_completion_slot,
  output logic wf_completion_fault,
  output logic [5:0]  wf_completion_fault_code,
  output logic [63:0] wf_completion_pc,
  output logic [63:0] wf_completion_retired_count,
  // bootstrap init channels
  input  logic sgpr_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sgpr_init_slot,
  input  logic [7:0]  sgpr_init_addr, input logic [31:0] sgpr_init_data,
  output logic sgpr_init_ready,
  input  logic pred_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] pred_init_slot,
  input  logic [3:0]  pred_init_addr, input logic [31:0] pred_init_data,
  output logic pred_init_ready,
  input  logic vgpr_init_valid,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] vgpr_init_slot,
  input  logic [7:0]  vgpr_init_addr, input logic [4:0] vgpr_init_lane,
  input  logic [31:0] vgpr_init_data, output logic vgpr_init_ready,
  // scheduler debug
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_allocated,
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_issueable,
  output logic [RESIDENT_WAVEFRONTS_PER_CU-1:0] dbg_inflight,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] dbg_rr_ptr,
  output logic sched_issue_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sched_issue_wfid,
  output logic [63:0] sched_issue_pc, sched_issue_insn,
  output logic [1:0]  sched_issue_pipe,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sched_rr_before,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] sched_rr_after,
  output logic [31:0] dbg_resident_count, dbg_ready_count,
                      dbg_issueable_count,
  // PMCs
  output logic [PMC_WIDTH-1:0] PMC_CYCLES, PMC_RESIDENT_CYCLES,
    PMC_ISSUE_CYCLES, PMC_SCALAR_ISSUES, PMC_VECTOR_ISSUES,
    PMC_NO_ISSUE_CYCLES, PMC_FETCH_WAIT_CYCLES, PMC_PIPE_BUSY_CYCLES,
    PMC_WAVEFRONTS_LAUNCHED, PMC_WAVEFRONTS_COMPLETED,
    PMC_WAVEFRONTS_FAULTED, PMC_CONTEXT_SWITCHES,
    PMC_PREDICATE_WRITES, PMC_DIVERGENT_BRANCHES, PMC_UNIFORM_BRANCHES,
    PMC_RECONV_EVENTS, PMC_MASK_PUSHES, PMC_MASK_POPS,
    PMC_MASK_STACK_MAX_DEPTH, PMC_BREAK_EVENTS, PMC_CONTINUE_EVENTS,
    PMC_EARLY_RETURN_LANES,
  // traces
  output logic trace_s_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] trace_s_wfid,
  output logic [63:0] trace_s_pc, trace_s_insn, trace_s_next_pc,
  output logic trace_s_sgpr_we, output logic [7:0] trace_s_sgpr_addr,
  output logic [31:0] trace_s_sgpr_wdata,
  output logic [31:0] trace_s_exec, trace_s_live,
  output logic trace_v_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] trace_v_wfid,
  output logic [63:0] trace_v_pc, trace_v_insn, trace_v_next_pc,
  output logic [31:0] trace_v_exec_mask, trace_v_effective_mask,
  output logic [3:0]  trace_v_pred_idx,
  output logic [31:0] trace_v_live,
  output logic        trace_v_pred_we,
  output logic [3:0]  trace_v_pred_addr,
  output logic [31:0] trace_v_pred_wmask, trace_v_pred_value,
  output logic trace_m_valid,
  output logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] trace_m_wfid,
  output logic [3:0]  trace_m_kind,
  output logic [63:0] trace_m_pc,
  output logic [31:0] trace_m_old_exec, trace_m_new_exec,
  output logic [31:0] trace_m_old_live, trace_m_new_live,
  output logic [$clog2(MASK_STACK_DEPTH+1)-1:0] trace_m_sp_before,
  output logic [$clog2(MASK_STACK_DEPTH+1)-1:0] trace_m_sp_after,
  output logic [1:0]  trace_m_ftype,
  output logic        trace_m_push, trace_m_pop,
  output logic [31:0] trace_m_pending,
  output logic [63:0] trace_m_target,
  output logic        trace_m_fault,
  output logic [5:0]  trace_m_fcode,
  // debug peek
  output logic [63:0] dbg_last_compl_pc,
  output scigpu_types_pkg::state_e dbg_state,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] dbg_wf_sel,
  input  logic [7:0]  dbg_sgpr_addr, output logic [31:0] dbg_sgpr_data,
  input  logic [3:0]  dbg_pred_addr, output logic [31:0] dbg_pred_data,
  input  logic [7:0]  dbg_vgpr_addr, input logic [4:0] dbg_vgpr_lane,
  output logic [31:0] dbg_vgpr_data,
  output logic [31:0] dbg_exec_data, dbg_live_data,
  input  logic [$clog2(RESIDENT_WAVEFRONTS_PER_CU)-1:0] dbg_mc_slot,
  output logic [31:0] dbg_mc_sp,
  output logic [31:0] dbg_mc_top_parent, dbg_mc_top_maska, dbg_mc_top_maskb
);

  scigpu_m5_cu #(
    .SGPR_COUNT(SGPR_COUNT), .VGPR_COUNT(VGPR_COUNT),
    .SIMD_LANES(SIMD_LANES),
    .RESIDENT_WAVEFRONTS_PER_CU(RESIDENT_WAVEFRONTS_PER_CU),
    .MASK_STACK_DEPTH(MASK_STACK_DEPTH), .PMC_WIDTH(PMC_WIDTH)
  ) u_core ( .* );

endmodule
